Begin;
DROP TABLE IF EXISTS USERS,
COMMENT,
POSTS CASCADE;
CREATE TABLE USERS (
    id SERIAL PRIMARY KEY,
    USERNAME VARCHAR(25) UNIQUE,
    EMAIL TEXT NOT NULL,
    USER_PASSWORD TEXT NOT NULL,
    PICTURE TEXT DEFAULT 'https://i.pinimg.com/originals/a3/9c/1e/a39c1e2636f0f319bc4a46d06ebed079.jpg'
);
CREATE TABLE POSTS (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER REFERENCES USERS(id) ON DELETE CASCADE,
    POST_CONTENT TEXT NOT NULL,
    VOTES INTEGER DEFAULT 1,
    POST_TIME timestamp DEFAULT current_timestamp,
    POST_IMG TEXT 
);
CREATE TABLE COMMENT (
    ID SERIAL PRIMARY KEY,
    USER_ID INTEGER REFERENCES USERS(id) ON DELETE CASCADE,
    POST_ID INTEGER REFERENCES POSTS(ID) ON DELETE CASCADE,
    VOTES INTEGER DEFAULT 1,
    POST_TIME timestamp DEFAULT current_timestamp,
    COMMENT_CONTENT TEXT NOT NULL
);
INSERT INTO USERS(USERNAME,USER_PASSWORD,EMAIL) VALUES('reem','123456','sh@gmail.com');
INSERT INTO POSTS (USER_ID,POST_CONTENT,POST_IMG,vote)VALUES(1,'Reem','https://i.pinimg.com/564x/ec/0c/01/ec0c01d5fdffd487415462445ac4a299.jpg');
COMMIT;